package io.github.zalexanninev15.tokitoki.domain.model

/** Which backend a piece of content came from. */
enum class SourceKind { MASTODON, MISSKEY, TELEGRAM }

/**
 * Identity of a connected account. [localId] is generated by us and is stable across
 * token refreshes; [handle] is for display only and may change server-side.
 */
data class AccountRef(
    val localId: String,
    val source: SourceKind,
    val host: String,
    val handle: String,
)

/**
 * Globally unique identity of a feed item.
 *
 * The remote id alone is NOT unique: two Mastodon instances happily use the same
 * snowflake values, and a Telegram message id is only unique within its chat.
 */
data class FeedItemId(
    val source: SourceKind,
    val accountLocalId: String,
    val remoteId: String,
) {
    /** Stable string form, used as the Room primary key. */
    val value: String get() = "${source.name}|$accountLocalId|$remoteId"

    companion object {
        fun parse(value: String): FeedItemId? {
            val parts = value.split('|', limit = 3)
            if (parts.size != 3) return null
            val source = SourceKind.entries.firstOrNull { it.name == parts[0] } ?: return null
            return FeedItemId(source, parts[1], parts[2])
        }
    }
}

data class Author(
    val remoteId: String,
    val displayName: String,
    /** `@user@host` for the fediverse, channel @username or title for Telegram. */
    val handle: String,
    val avatarUrl: String?,
    val isBot: Boolean = false,
)

enum class MediaKind { IMAGE, ANIMATED, VIDEO, AUDIO, FILE }

data class MediaAttachment(
    val kind: MediaKind,
    /** Full-size URL. For Telegram this is resolved lazily and may be null until downloaded. */
    val url: String?,
    val previewUrl: String?,
    /** Alt text. Mastodon and Misskey both expose it; Telegram does not. */
    val description: String?,
    val width: Int?,
    val height: Int?,
    val blurHash: String? = null,
    val sizeBytes: Long? = null,
) {
    /** Aspect ratio for the lazy list placeholder, so the layout does not jump on load. */
    val aspectRatio: Float?
        get() {
            val w = width ?: return null
            val h = height ?: return null
            if (w <= 0 || h <= 0) return null
            return w.toFloat() / h.toFloat()
        }
}

/**
 * The unifying text representation.
 *
 * Mastodon delivers HTML, Misskey delivers MFM, Telegram delivers plain text plus a list
 * of entity ranges. All three are normalised to plain text + spans so that exactly one
 * renderer exists in the UI layer.
 */
data class RichText(
    val plain: String,
    val spans: List<TextSpan> = emptyList(),
) {
    companion object {
        val EMPTY = RichText("")
        fun plain(text: String) = RichText(text)
    }
}

enum class SpanKind { LINK, MENTION, HASHTAG, BOLD, ITALIC, STRIKETHROUGH, CODE, QUOTE, CUSTOM_EMOJI }

/**
 * Half-open range `[start, end)` over [RichText.plain], indexed in UTF-16 code units to
 * match what Compose's AnnotatedString expects.
 */
data class TextSpan(
    val start: Int,
    val end: Int,
    val kind: SpanKind,
    /** URL for LINK, acct for MENTION, tag for HASHTAG, shortcode for CUSTOM_EMOJI. */
    val target: String? = null,
) {
    init {
        require(start >= 0) { "span start must be >= 0, was $start" }
        require(end >= start) { "span end ($end) must be >= start ($start)" }
    }

    val length: Int get() = end - start
}

data class FeedItem(
    val id: FeedItemId,
    val author: Author,
    /** Publication time as epoch milliseconds; also the merge sort key. */
    val createdAtEpochMillis: Long,
    val text: RichText,
    val media: List<MediaAttachment> = emptyList(),
    /** Mastodon spoiler_text / Misskey cw. Telegram has no equivalent. */
    val contentWarning: String? = null,
    /**
     * Canonical public URL, or null when none exists — which is the real case for
     * private Telegram channels. The copy-link action must be disabled, not faked.
     */
    val canonicalUrl: String? = null,
    val inReplyTo: FeedItemId? = null,
    val quoted: FeedItem? = null,
    /** Set for a boost/renote/forward that carries no commentary of its own. */
    val reposted: FeedItem? = null,
    val repostedBy: Author? = null,
    /** Null when the source has no notion of favourites or boosts. */
    val interactions: PostInteractions? = null,
    /**
     * Instance emoji used in this post: shortcode without colons -> image URL.
     *
     * Carried per post rather than fetched globally because every instance defines its
     * own set, and a boost can bring emoji from a server the reader has never seen.
     */
    val customEmojis: Map<String, String> = emptyMap(),
) {
    val hasMedia: Boolean get() = media.isNotEmpty() || reposted?.media?.isNotEmpty() == true

    /** The item whose body should actually be rendered. */
    val displayed: FeedItem get() = reposted ?: this
}
